### ISSUE TITLE
java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by yvolk** [andstatus/andstatus#301]
We got this Crash report:
```
ANDROID_VERSION=5.0.2
APP_VERSION_NAME=19.2
BRAND=motorola
PHONE_MODEL=XT1072
STACK_TRACE=java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:422)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
        at java.lang.Thread.run(Thread.java:818)
```
As this discussion suggests http://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin

" The issue cannot be avoided - you will encounter it if your app runs in the background. You can mitigate by taking a wakelock, and prevent the device from sleeping, but that is a different story altogether, and a new headache, and maybe another talk in another con. You can minimize the problem by reducing GC calls - making the scenario less likely. tips are in the slides." ...

**Comment by yvolk** [comment]
Looks like this is Android system problem. And it's being fixed by Android core team.

**Comment by srinukodi** [comment]
Hi yvolk,

Is this issue fixed from Android core.
Because we are still seeing this issue on API23 onwards on emulators especially. Or can you please guide me what to do in-order to get rid off this issue ?


-Srinu

**Comment by yvolk** [comment]
@srinukodi As link from my first post tells: the problem was solved in Android firmware.
I personally never encountered such a crash, so I cannot tell otherwise.
